/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_internal_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Bulk
         * @description Clear a morning's queue in one click.
         *
         *     Partial success is the expected outcome, not an error: one already-decided
         *     or expired item must not sink the other forty-nine. Each skip says why.
         */
        post: operations["decide_bulk_v1_approvals_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_v1_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_v1_approvals__approval_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_v1_approvals__approval_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Content */
        get: operations["list_content_v1_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Plan and queue a content run.
         *
         *     The run starts as a single strategist task. How many pieces a vehicle
         *     deserves is not knowable until something has looked at it, so the rest of
         *     the DAG is spawned by the strategist rather than guessed here.
         */
        post: operations["generate_v1_content_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite */
        post: operations["accept_invite_v1_invites_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Member */
        patch: operations["patch_member_v1_members__user_id__patch"];
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Plan and queue a run. 202, not 201 — the work has not happened yet.
         */
        post: operations["start_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_v1_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_v1_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Tenants
         * @description Which workspaces does the caller belong to?
         *
         *     Runs before any tenant context exists, so it goes through a SECURITY
         *     DEFINER function scoped to one user id — see 0003_bootstrap.sql. The
         *     browser has no direct table access since 0006_sales_core.sql, so this
         *     endpoint is how every client learns its workspaces.
         */
        get: operations["list_my_tenants_v1_tenants_get"];
        put?: never;
        /**
         * Create Tenant
         * @description Create a workspace and make the caller its owner.
         *
         *     Both writes happen inside app.create_tenant_with_owner (0003_bootstrap.sql).
         *     They cannot be done from here: the caller is not yet a member of the tenant
         *     they are creating, so RLS correctly refuses every statement. A tenant with
         *     no owner would also be unreachable, so the two writes are never allowed to
         *     diverge into separate application statements.
         */
        post: operations["create_tenant_v1_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tenant */
        get: operations["get_tenant_v1_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Tenant */
        patch: operations["update_tenant_v1_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/v1/tenants/{tenant_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invite
         * @description Mint a signed, expiring invitation.
         *
         *     Signed rather than stored: there is no invitations table to keep clean, and
         *     a leaked link expires on its own. Single use is enforced at redemption by
         *     the unique (tenant_id, user_id) on memberships — replaying a link cannot
         *     create a second membership or silently change someone's role.
         */
        post: operations["create_invite_v1_tenants__tenant_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tenant_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_tenants__tenant_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tenant_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_v1_tenants__tenant_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tenant_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Usage */
        get: operations["tenant_usage_v1_tenants__tenant_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vehicles */
        get: operations["list_vehicles_v1_vehicles_get"];
        put?: never;
        /** Create Vehicle */
        post: operations["create_vehicle_v1_vehicles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Import
         * @description Import under the mapping the human confirmed.
         *
         *     Rows are inserted one at a time, each in its own transaction. A single
         *     statement would be faster and would also mean row 12's duplicate VIN throws
         *     away the other 49 — which is the behaviour this endpoint exists to avoid.
         */
        post: operations["run_import_v1_vehicles_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Read the file and guess what each column is.
         *
         *     Nothing is written. The response is what the confirmation screen renders,
         *     including the sample rows — a mapping is far easier to check against three
         *     real rows than against a column name.
         */
        post: operations["preview_v1_vehicles_import_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles/stock-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Report
         * @description Aging and content coverage — the report that answers 'what is not selling
         *     and what have we never posted about'.
         */
        get: operations["stock_report_v1_vehicles_stock_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles/{vehicle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vehicle */
        get: operations["get_vehicle_v1_vehicles__vehicle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Vehicle */
        patch: operations["update_vehicle_v1_vehicles__vehicle_id__patch"];
        trace?: never;
    };
    "/v1/vehicles/{vehicle_id}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Price
         * @description Set the list price. Always writes history, always emits.
         *
         *     Published content shows a price. Changing it without telling anything else
         *     leaves posts and ads quoting a number the dealer no longer honours, so the
         *     history row and the event are part of the same transaction as the update.
         */
        post: operations["change_price_v1_vehicles__vehicle_id__price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles/{vehicle_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Status
         * @description Change availability.
         *
         *     Selling a car emits `vehicle.sold`, whose handler cancels every scheduled
         *     content item and paused ad that references it. Marketing a car that is gone
         *     is the most visible way this product can embarrass a dealer, so the cascade
         *     is an event rather than something each caller has to remember.
         */
        post: operations["change_status_v1_vehicles__vehicle_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalOut */
        ApprovalOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at?: string | null;
            /** Decision Note */
            decision_note?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Required Role */
            required_role: string;
            /** Run Id */
            run_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "expired";
            /** Summary */
            summary: string;
        };
        /** Body_preview_v1_vehicles_import_preview_post */
        Body_preview_v1_vehicles_import_preview_post: {
            /** File */
            file: string;
        };
        /** Body_run_import_v1_vehicles_import_post */
        Body_run_import_v1_vehicles_import_post: {
            /** File */
            file: string;
            /**
             * Mapping
             * @description confirmed {"header": "field"} JSON
             */
            mapping: string;
        };
        /** BulkDecision */
        BulkDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Ids */
            ids: string[];
            /** Note */
            note?: string | null;
        };
        /** BulkResult */
        BulkResult: {
            /** Decided */
            decided: string[];
            /** Skipped */
            skipped: {
                [key: string]: string;
            };
        };
        /** ContentItemOut */
        ContentItemOut: {
            /**
             * Assets
             * @default 0
             */
            assets: number;
            /** Concept */
            concept: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Locales */
            locales?: string[];
            /** Published At */
            published_at?: string | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** Run Id */
            run_id: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Status */
            status: string;
            /** Vehicle Id */
            vehicle_id: string | null;
        };
        /** Decision */
        Decision: {
            /** Note */
            note?: string | null;
        };
        /** GenerateAccepted */
        GenerateAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Count
             * @default 8
             */
            count: number;
            /** Locales */
            locales?: string[];
            /**
             * Objective
             * @default sell this stock
             */
            objective: string;
            /** Vehicle Ids */
            vehicle_ids?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Created */
            created: number;
            /** Errors */
            errors: components["schemas"]["RowError"][];
        };
        /** InviteAccept */
        InviteAccept: {
            /** Token */
            token: string;
        };
        /** InviteCreate */
        InviteCreate: {
            /** Email */
            email: string;
            /**
             * Role
             * @default marketer
             * @enum {string}
             */
            role: "viewer" | "sales" | "marketer" | "manager" | "admin" | "owner";
        };
        /** InviteOut */
        InviteOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "sales" | "marketer" | "manager" | "admin" | "owner";
            /** Token */
            token: string;
        };
        /** MeOut */
        MeOut: {
            /** Accepting Chats */
            accepting_chats: boolean;
            /** Permissions */
            permissions: string[];
            /** Role */
            role: string;
            /** Scope */
            scope: string;
            /** Team Ids */
            team_ids: string[];
            tenant: components["schemas"]["MeTenant"];
            user: components["schemas"]["MeUser"];
        };
        /** MePatch */
        MePatch: {
            /** Accepting Chats */
            accepting_chats: boolean;
        };
        /** MeTenant */
        MeTenant: {
            /** Accent Color */
            accent_color?: string | null;
            /** Currency */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
        };
        /** MeUser */
        MeUser: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** MemberPatch */
        MemberPatch: {
            /** Accepting Chats */
            accepting_chats?: boolean | null;
            /** Languages */
            languages?: ("ar" | "en" | "fr")[] | null;
            /** Role */
            role?: ("viewer" | "sales" | "marketer" | "manager" | "admin" | "owner") | null;
            /** Team Ids */
            team_ids?: string[] | null;
        };
        /** Money */
        Money: {
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
        };
        /** PriceChange */
        PriceChange: {
            /** Amount Minor */
            amount_minor: number;
            /** Reason */
            reason: string;
        };
        /** RowError */
        RowError: {
            /** Message */
            message: string;
            /**
             * Row
             * @description 1-based row number in the file, excluding the header.
             */
            row: number;
        };
        /** RunCreate */
        RunCreate: {
            /** Autonomy */
            autonomy?: ("copilot" | "assisted" | "autopilot") | null;
            /** Goal */
            goal: string;
            /** Goal Input */
            goal_input?: {
                [key: string]: unknown;
            };
            /** Tasks */
            tasks?: components["schemas"]["TaskSpec"][] | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Autonomy */
            autonomy: string;
            /** Cost Usd */
            cost_usd: number;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Goal */
            goal: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "planning" | "running" | "waiting_approval" | "completed" | "partial" | "failed" | "cancelled";
            /** Summary */
            summary?: string | null;
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
            /** Trigger Type */
            trigger_type: string;
        };
        /** RunOut */
        RunOut: {
            /** Autonomy */
            autonomy: string;
            /** Cost Usd */
            cost_usd: number;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Goal */
            goal: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "planning" | "running" | "waiting_approval" | "completed" | "partial" | "failed" | "cancelled";
            /** Summary */
            summary?: string | null;
            /** Trigger Type */
            trigger_type: string;
        };
        /** StatusChange */
        StatusChange: {
            /** Reason */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "available" | "reserved" | "sold" | "archived";
        };
        /** StockRow */
        StockRow: {
            /** Days In Stock */
            days_in_stock: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Content At */
            last_content_at: string | null;
            /** Make */
            make: string;
            /** Model */
            model: string;
            price: components["schemas"]["Money"] | null;
            /** Published Content Count */
            published_content_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "available" | "reserved" | "sold" | "archived";
            /** Stock Number */
            stock_number: string | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Agent */
            agent: string;
            /** Attempts */
            attempts: number;
            /** Cost Usd */
            cost_usd: number;
            /** Depends On */
            depends_on: string[];
            /** Error */
            error?: string | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Task Key */
            task_key: string;
        };
        /**
         * TaskSpec
         * @description A task in a caller-supplied DAG. Skips planning entirely.
         */
        TaskSpec: {
            /** Agent */
            agent: string;
            /** Depends On */
            depends_on?: string[];
            /** Input */
            input?: {
                [key: string]: unknown;
            };
            /** Task Key */
            task_key: string;
        };
        /** TeamIn */
        TeamIn: {
            /**
             * Member Ids
             * @default []
             */
            member_ids: string[];
            /** Name */
            name: string;
        };
        /** TeamOut */
        TeamOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Member Ids */
            member_ids: string[];
            /** Name */
            name: string;
        };
        /** TenantCreate */
        TenantCreate: {
            /**
             * Country
             * @default AE
             */
            country: string;
            /**
             * Currency
             * @default AED
             */
            currency: string;
            /** Locales */
            locales?: string[];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Timezone
             * @default Asia/Dubai
             */
            timezone: string;
        };
        /** TenantOut */
        TenantOut: {
            /**
             * Autonomy Mode
             * @enum {string}
             */
            autonomy_mode: "copilot" | "assisted" | "autopilot";
            /** Autonomy Rules */
            autonomy_rules: {
                [key: string]: unknown;
            };
            /** Country */
            country: string;
            /** Currency */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locales */
            locales: string[];
            /** Name */
            name: string;
            /** Plan */
            plan: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
        };
        /** TenantUpdate */
        TenantUpdate: {
            /** Autonomy Mode */
            autonomy_mode?: ("copilot" | "assisted" | "autopilot") | null;
            /** Autonomy Rules */
            autonomy_rules?: {
                [key: string]: unknown;
            } | null;
            /** Locales */
            locales?: string[] | null;
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** UsageOut */
        UsageOut: {
            /** Budget Usd */
            budget_usd: number;
            /** Month */
            month: string;
            /** Remaining Usd */
            remaining_usd: number;
            /** Spent Usd */
            spent_usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehicleCreate */
        VehicleCreate: {
            /** Engine */
            engine?: string | null;
            /** Exterior Color */
            exterior_color?: string | null;
            /** Features */
            features?: string[];
            /** Fuel */
            fuel?: string | null;
            /** Interior Color */
            interior_color?: string | null;
            /** Location */
            location?: string | null;
            /** Make */
            make: string;
            /**
             * Mileage Km
             * @default 0
             */
            mileage_km: number;
            /** Min Price Minor */
            min_price_minor?: number | null;
            /** Model */
            model: string;
            /** Model Year */
            model_year?: number | null;
            /** Price Minor */
            price_minor?: number | null;
            /** Seats */
            seats?: number | null;
            /** Specs */
            specs?: {
                [key: string]: unknown;
            };
            /**
             * Steering
             * @default lhd
             * @enum {string}
             */
            steering: "lhd" | "rhd";
            /** Stock Number */
            stock_number?: string | null;
            /** Target Markets */
            target_markets?: string[];
            /** Transmission */
            transmission?: string | null;
            /** Trim */
            trim?: string | null;
            /**
             * Vehicle Condition
             * @default new
             * @enum {string}
             */
            vehicle_condition: "new" | "used" | "certified";
            /** Vin */
            vin?: string | null;
        };
        /**
         * VehicleOut
         * @description The internal view. Only staff endpoints return this.
         */
        VehicleOut: {
            /** Engine */
            engine?: string | null;
            /** Exterior Color */
            exterior_color?: string | null;
            /** Features */
            features: string[];
            /** Fuel */
            fuel?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Interior Color */
            interior_color?: string | null;
            /**
             * Listed At
             * Format: date-time
             */
            listed_at: string;
            /** Location */
            location?: string | null;
            /** Make */
            make: string;
            /** Mileage Km */
            mileage_km: number;
            min_price?: components["schemas"]["Money"] | null;
            /** Model */
            model: string;
            /** Model Year */
            model_year?: number | null;
            price?: components["schemas"]["Money"] | null;
            /** Seats */
            seats?: number | null;
            /** Sold At */
            sold_at?: string | null;
            /** Source */
            source: string;
            /** Specs */
            specs: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "available" | "reserved" | "sold" | "archived";
            /**
             * Steering
             * @enum {string}
             */
            steering: "lhd" | "rhd";
            /** Stock Number */
            stock_number?: string | null;
            /** Target Markets */
            target_markets: string[];
            /** Transmission */
            transmission?: string | null;
            /** Trim */
            trim?: string | null;
            /**
             * Vehicle Condition
             * @enum {string}
             */
            vehicle_condition: "new" | "used" | "certified";
            /** Vin */
            vin?: string | null;
        };
        /** VehicleUpdate */
        VehicleUpdate: {
            /** Engine */
            engine?: string | null;
            /** Exterior Color */
            exterior_color?: string | null;
            /** Features */
            features?: string[] | null;
            /** Fuel */
            fuel?: string | null;
            /** Interior Color */
            interior_color?: string | null;
            /** Location */
            location?: string | null;
            /** Mileage Km */
            mileage_km?: number | null;
            /** Min Price Minor */
            min_price_minor?: number | null;
            /** Seats */
            seats?: number | null;
            /** Specs */
            specs?: {
                [key: string]: unknown;
            } | null;
            /** Target Markets */
            target_markets?: string[] | null;
            /** Transmission */
            transmission?: string | null;
            /** Trim */
            trim?: string | null;
        };
        /** MemberOut */
        dealerai__routes__team__MemberOut: {
            /** Accepting Chats */
            accepting_chats: boolean;
            /** Avatar Url */
            avatar_url: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Languages */
            languages: string[];
            /** Name */
            name: string | null;
            /** Open Conversations */
            open_conversations: number;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "sales" | "marketer" | "manager" | "admin" | "owner";
            /** Team Ids */
            team_ids: string[];
        };
        /** MemberOut */
        dealerai__routes__tenants__MemberOut: {
            /** Email */
            email?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "sales" | "marketer" | "manager" | "admin" | "owner";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_internal_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_approvals_v1_approvals_get: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected" | "expired";
                limit?: number;
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_bulk_v1_approvals_bulk_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_v1_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_v1_approvals__approval_id__approve_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_v1_approvals__approval_id__reject_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_v1_content_get: {
        parameters: {
            query?: {
                run_id?: string | null;
                status?: string | null;
                limit?: number;
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_v1_content_generate_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_v1_invites_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dealerai__routes__tenants__MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_v1_me_patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_members_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dealerai__routes__team__MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_member_v1_members__user_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dealerai__routes__team__MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                status?: ("planning" | "running" | "waiting_approval" | "completed" | "partial" | "failed" | "cancelled") | null;
                limit?: number;
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_v1_runs_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_v1_teams_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_v1_teams_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_tenants_v1_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"][];
                };
            };
        };
    };
    create_tenant_v1_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_v1_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tenant_v1_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_v1_tenants__tenant_id__invites_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_tenants__tenant_id__members_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dealerai__routes__tenants__MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_tenants__tenant_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_usage_v1_tenants__tenant_id__usage_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vehicles_v1_vehicles_get: {
        parameters: {
            query?: {
                status?: ("draft" | "available" | "reserved" | "sold" | "archived") | null;
                make?: string | null;
                model?: string | null;
                max_price_minor?: number | null;
                stale_days?: number | null;
                /** @description matches make, model or stock number */
                q?: string | null;
                limit?: number;
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vehicle_v1_vehicles_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_import_v1_vehicles_import_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run_import_v1_vehicles_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_v1_vehicles_import_preview_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_v1_vehicles_import_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_report_v1_vehicles_stock_report_get: {
        parameters: {
            query?: {
                min_days?: number;
                /** @description only vehicles with no published content */
                uncovered_only?: boolean;
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vehicle_v1_vehicles__vehicle_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vehicle_v1_vehicles__vehicle_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_price_v1_vehicles__vehicle_id__price_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_v1_vehicles__vehicle_id__status_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
